root: ./Curriculum
structure:
  summary: README.md
  langs:
    en:
      title: Project Athena Curriculum
      sections:
        - title: Module 1 - Ethics and Legal
          path: ./Module 1 - Ethics and Legal
          sections:
            - title: Ethics
              path: ./Module 1 - Ethics and Legal/lectures/ethics.md
